apiVersion: v1
kind: pod
metadata:
  name: empty-dir-demo
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountpath: /var/log/nginx
      name: nginx-logs
  - name: almalinux
    image: almalinux:9
    command: ["sleep","1000"]
    volumeMounts:
    - mountpath: /mnt/nginx
      name: nginx-logs
      readOnly: true
  
  volumes:
  - name: nginx-logs
    empty-dir:
      size-limit: 100Mi