apiVersion: v1
kind: Pod
metadata:
  name: multicontainers
  labels:
    purpose: multi-containers
spec: 
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux
    command: ["sleep","1000"]