apiVersion: v1
kind: Pod
metadata:
  name: error-checking
spec:
  containers:
  # this gives the image pull backoff error because that image is not present
  #  name: nginx
  #  image: akansj
  
  # this will give crashloop back off errror because it doesn't have command to run
  - name: almalinux
    image: almalinux:9
  