apiVersion: v1
kind: Pod
metadata:
  name: resource_demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "68Mi"
        cpu: "100m"
        #provide more than or equal to requests
      limits:
        memory: "68Mi"
        cpu: "120m"