apiVersion: v1
kind: service
metadata:
  name: nginx
spec:
  selector:
    project: roboshop
    component: frontend
    environment: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
