apiVersion: apps/v1
kind: replicaSet
metadata:
  name: nginx
  # these are replicaset labels
  labels:
    purpose: rs-demo
    project: roboshop
spec:
  replicas: 3
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: rs-demo
      project: roboshop
  # pod definition
  templates:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx